// Lista de assets (script clásico, no usar export/import).
// Cada item puede exponer slug y category para navegación directa desde la home.
window.ASSETS = [
  { label: "Dinosaurio feliz", slug: "dinosaurio", category: "dinosaurios", src: "assets/dinosaur-v2.png", featured: true },
  { label: "Gato curioso", slug: "gato", category: "animales", src: "assets/cat-v2.png", featured: true },
  { label: "Perro juguetón", slug: "perro", category: "animales", src: "assets/dog-v2.png", featured: true },
  { label: "Auto rojo", slug: "auto", category: "vehiculos", src: "assets/car-v2.png", featured: true },
  { label: "Árbol de navidad", slug: "arbol-navidad", category: "navidad", src: "assets/christmas-tree-v2.png", featured: true },
  { label: "Mariposa", slug: "mariposa", category: "animales", src: "assets/butterfly-v2.png", featured: true },
  { label: "Cohete", slug: "cohete", category: "vehiculos", src: "assets/rocket-v2.png", featured: true },
  { label: "Princesa", slug: "princesa", category: "princesas", src: "assets/princess-v2.png", featured: true },
  { label: "Unicornio", slug: "unicornio", category: "fantasia", src: "assets/unicorn-v2.png", featured: true },
  { label: "Castillo", slug: "castillo", category: "fantasia", src: "assets/castle-v2.png", featured: true },
  { label: "Elefante alegre", slug: "elefante", category: "animales", src: "assets/elefante.png" },
  { label: "Conejo saltarín", slug: "conejo", category: "animales", src: "assets/conejo.png" },
  { label: "Pez sonriente", slug: "pez", category: "animales", src: "assets/pez.png" },
  { label: "Búho amable", slug: "buho", category: "animales", src: "assets/buho.png" },
  { label: "Camión feliz", slug: "camion", category: "vehiculos", src: "assets/camion.png" },
  { label: "Avión divertido", slug: "avion", category: "vehiculos", src: "assets/avion.png" },
  { label: "Barco de vela", slug: "barco", category: "vehiculos", src: "assets/barco.png" },
  { label: "Tren juguete", slug: "tren", category: "vehiculos", src: "assets/tren.png" },
  { label: "Muñeco de nieve", slug: "muneco-nieve", category: "navidad", src: "assets/muneco-nieve.png" },
  { label: "Regalo navideño", slug: "regalo-navidad", category: "navidad", src: "assets/regalo-navidad.png" },
  { label: "Campana navideña", slug: "campana-navidad", category: "navidad", src: "assets/campana-navidad.png" },
  { label: "Dragón bebé", slug: "dragon", category: "fantasia", src: "assets/dragon.png" },
  { label: "Hada mágica", slug: "hada", category: "fantasia", src: "assets/hada.png" },
  { label: "Sirena feliz", slug: "sirena", category: "fantasia", src: "assets/sirena.png" },
  { label: "Triceratops", slug: "triceratops", category: "dinosaurios", src: "assets/triceratops.png" },
  { label: "Brontosaurio", slug: "brontosaurio", category: "dinosaurios", src: "assets/brontosaurio.png" },
  { label: "Pterodáctilo", slug: "pterodactilo", category: "dinosaurios", src: "assets/pterodactilo.png" },
  { label: "Corona real", slug: "corona-real", category: "princesas", src: "assets/corona-real.png" },
  { label: "Carruaje real", slug: "carruaje-real", category: "princesas", src: "assets/carruaje-real.png" },
  { label: "Vestido de princesa", slug: "vestido-princesa", category: "princesas", src: "assets/vestido-princesa.png" },
  { label: "Pony mágico", slug: "pony-magico", category: "fantasia", src: "assets/pony1.png" },
  { label: "Pony princesa", slug: "pony-princesa", category: "princesas", src: "assets/pony2.png" },
  { label: "Pony 3", slug: "pony-3", category: "fantasia", src: "assets/pony3.png" },
  { label: "Pony 4", slug: "pony-4", category: "fantasia", src: "assets/pony4.png" },
  { label: "Casa 1", slug: "casa-1", category: "navidad", src: "assets/house1.png" },
  { label: "Casa 2", slug: "casa-2", category: "navidad", src: "assets/house2.png" },
  { label: "Casa 3", slug: "casa-3", category: "navidad", src: "assets/house3.png" },
  { label: "Casa 4", slug: "casa-4", category: "vehiculos", src: "assets/house4.png" },
  { label: "Casa 5", slug: "casa-5", category: "navidad", src: "assets/house5.png" },
  { label: "Paisaje 1", slug: "paisaje-1", category: "animales", src: "assets/landscape1.png" },
  { label: "Paisaje 2", slug: "paisaje-2", category: "animales", src: "assets/landscape2.png" },
  { label: "Paisaje 3", slug: "paisaje-3", category: "animales", src: "assets/landscape3.png" },
  { label: "Paisaje 4", slug: "paisaje-4", category: "animales", src: "assets/landscape4.png" },
  { label: "Paisaje 5", slug: "paisaje-5", category: "animales", src: "assets/landscape5.png" },
  { label: "Casa simple", slug: "casa-simple", category: "navidad", src: "assets/outline_house.png" },
  { label: "Casa flotante", slug: "casa-flotante", category: "vehiculos", src: "assets/houseboat.png" },
  { label: "Bungaló", slug: "bungalo", category: "vehiculos", src: "assets/bungalow.png" },
  { label: "Catedral gótica", slug: "catedral-gotica", category: "fantasia", src: "assets/gothic2.png" },
  { label: "Casa entramada", slug: "casa-entramada", category: "fantasia", src: "assets/half_timbered.png" },
  { label: "Gradería", slug: "graderia", category: "vehiculos", src: "assets/grandstand.png" },
  { label: "Montañas Urales", slug: "montanas-urales", category: "vehiculos", src: "assets/ural_mountain.png" },
  { label: "Bosque de Argonne", slug: "bosque-argonne", category: "animales", src: "assets/argonne_forest.png" },
  { label: "Bosque Negro", slug: "bosque-negro", category: "animales", src: "assets/black_forest.png" }
];
