// Generated by scripts/build_catalog.py.
import 'models.dart';

const catalogCategories = <Category>[
  Category("animales", "Animales"),
  Category("vehiculos", "Vehículos"),
  Category("navidad", "Navidad"),
  Category("fantasia", "Fantasía"),
  Category("dinosaurios", "Dinosaurios"),
  Category("princesas", "Princesas"),
  Category("casas", "Casas"),
  Category("paisajes", "Paisajes"),
];
