"""Produces per-image checklist records from measured evidence and visual findings."""
from pathlib import Path
import hashlib
import json
import csv
from collections import Counter

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs/qa-evidence/2026-10-07/artwork-checklist'
TEXT_MARKS = {
    'gabby-pintando': 'Crédito pequeño en el pie.',
    'gabby-gato-espacial': 'Título de marca y sitio impreso en el pie.',
    'gabby-leyendo': 'Coloriage.com impreso en el pie.',
    'gabby-gato-simple': 'GABBY CHAT en la cabecera.',
    'gabby-amigos': 'GABBY CHAT en la cabecera.',
    'gabby-sala': 'FREE PRINTABLE, título de marca y GenColor.ai.',
    'gabby-gato-espacial-2': 'Título de marca y sitio en el pie.',
    'gabby-gato-caja': 'Título de marca y sitio en el pie.',
    'gabby-poster-amigos': 'Título de marca y Sketchok.com en el pie.',
    'gabby-casa-frontal': 'Sketchok.com en el pie.',
}
FRAGMENTED = ['pony-magico', 'pony-princesa', 'gabby-camping', 'gabby-pintando', 'gabby-amigos', 'gabby-cumpleanos', 'gabby-casa-magica']

def main():
    static = json.loads((OUT / 'static.json').read_text(encoding='utf-8'))['items']
    reports = {engine: json.loads((OUT / f'browser-{engine}.json').read_text(encoding='utf-8')) for engine in ['chromium', 'webkit']}
    extended = json.loads((OUT / 'extended-chromium.json').read_text(encoding='utf-8'))
    pipeline = json.loads((OUT / 'pipeline-differences.json').read_text(encoding='utf-8'))
    assert all(item['pixel_equal'] for item in pipeline['items']), 'Generated variants have different pixels'
    assert all(len(r['items']) == len(static) for r in [*reports.values(), extended]), 'Incomplete evidence'
    for report in reports.values():
        assert report['catalog_sha256'] == hashlib.sha256((ROOT / 'base_png/catalog.json').read_bytes()).hexdigest(), 'Catalog changed during audit'
        for filename, digest in report['editor_sha256'].items():
            assert digest == hashlib.sha256((ROOT / 'web' / filename).read_bytes()).hexdigest(), f'Editor changed: {filename}'
    by_engine = {engine: {i['slug']: i for i in r['items']} for engine, r in reports.items()}
    ex = {i['slug']: i for i in extended['items']}
    checklist = (ROOT / 'docs/CHECKLIST-IMAGENES-COLOREAR.md').read_text(encoding='utf-8')
    import re
    titles = {m.group(1): m.group(2) for m in re.finditer(r'^- \[ \] \*\*([TEP]-\d{2}) · ([^*]+)\*\*', checklist, re.M)}
    records = []
    summary = []
    for row in static:
        slug = row['slug']; browser = by_engine['chromium'][slug]; geometry = browser['geometry']; controls = {}
        assert hashlib.sha256((ROOT / row['files']['web']['path']).read_bytes()).hexdigest() == browser['source_sha256'], f'Asset changed: {slug}'
        for file in row['files'].values():
            assert hashlib.sha256((ROOT / file['path']).read_bytes()).hexdigest() == file['sha256'], f"Variant changed: {file['path']}"
        def set_control(control, status, evidence):
            controls[control] = {'status': status, 'evidence': evidence}
        set_control('T-01', 'Aprobado', 'Todas las variantes decodificadas por Pillow; contenido visible y carga en ambos editores web, Chrome y WebKit.')
        set_control('T-02', 'Pendiente' if 'flutter' in row['platforms'] else 'Aprobado', 'Rutas web y maestros presentes, carga HTTPS local comprobada. Flutter: archivo presente, incluido por pubspec y mismo hash que web; falta ejecución del paquete.' if 'flutter' in row['platforms'] else 'Rutas y maestros presentes; imagen y miniatura decodificadas; carga web comprobada.')
        set_control('T-03', 'Aprobado' if row['dimensions_pass'] else 'Fallido', 'Web ≤1200 px, miniatura ≤360 px; dimensiones y peso registrados para maestro y variante móvil cuando existe.')
        set_control('T-04', 'Aprobado' if row['aspect_delta'] <= .01 and row['master_aspect_delta'] <= .01 else 'Fallido', f"Diferencia web/miniatura={row['aspect_delta']:.6f}; maestro/web={row['master_aspect_delta']:.6f}. Variantes iguales al generador en contenido: 11 archivos difieren en codificación PNG, con los mismos píxeles. Revisión visual de hojas de contacto.")
        set_control('T-05', 'Aprobado', '62 slugs únicos; metadatos y recursos coherentes en el generador. 43 Flutter y 19 solo web declarados explícitamente.')
        set_control('T-06', 'Aprobado' if all(m.get('thumbnail_select') and m.get('dropdown_select') for m in ex[slug]['modes'].values()) else 'Fallido', 'Enlace directo en Chrome/WebKit; selección desde miniatura y evento del selector en Chrome, en ambos modos.')
        set_control('T-07', 'Aprobado', 'Sin píxeles de color por el criterio de canales; PNG aceptado por pincel. Esto no aprueba ruido gris ni procedencia.')
        set_control('T-08', 'Fallido' if slug == 'triceratops' else 'Pendiente', 'Cabeza y fondo exterior conectados: toque en (500,300) colorea ambos. Ver triceratops-probe/triceratops/paint-chromium-export.png.' if slug == 'triceratops' else 'Mapa de conectividad generado y revisado visualmente; falta validar mapa de regiones esperadas y conexiones intencionales. No se certifica cada contorno por una prueba del algoritmo.')
        set_control('T-09', 'Pendiente', 'Variante final probada; falta comparar continuidad de todos los contornos con el maestro y aprobar las conexiones previstas.')
        set_control('T-10', 'Fallido' if slug in FRAGMENTED else 'Pendiente', f"{len(geometry['regions'])} regiones detectadas, {geometry['regions_under_16px']} de menos de 16 píxeles. " + ('Fragmentación abundante y artefactos visibles en el mapa; limpiar el original y regenerar.' if slug in FRAGMENTED else 'No se certifica intención de cada detalle negro/gris; revisar regiones pequeñas antes de aprobar.'))
        set_control('T-11', 'Pendiente', 'Sin transparencia en la variante web; revisar si el exterior debe ser pintable y los márgenes. La salida PNG conserva el fondo del lienzo.')
        set_control('T-12', 'Bloqueado', 'Falta prueba con dedo en el dispositivo físico objetivo; las métricas de regiones no prueban facilidad de toque.')
        set_control('T-13', 'Fallido' if slug == 'triceratops' else 'Pendiente', f"Algoritmo recorrió las {len(geometry['regions'])} regiones geométricas: {geometry['mismatched_pixels']} píxeles discrepantes. " + ('La región de la cabeza incluye indebidamente el exterior.' if slug == 'triceratops' else 'Falta aprobar regiones esperadas; conectividad correcta no demuestra intención gráfica.'))
        set_control('T-14', 'Fallido' if slug == 'triceratops' else 'Pendiente', 'Fuga cabeza→exterior reproducida mediante puntero y exportación.' if slug == 'triceratops' else 'Mapas revisados; sin certificación completa de fugas hasta aprobar el mapa esperado.')
        set_control('T-15', 'Aprobado' if ex[slug]['modes']['paint'].get('line_click_protected') and geometry['damaged_line_pixels'] == 0 else 'Fallido', 'Todos los píxeles de máscara intactos en el barrido; toque sobre línea protegido en Chrome. Franja interior pendiente de revisión visual detallada.')
        set_control('T-16', 'Aprobado' if ex[slug]['modes']['paint'].get('recolor') and ex[slug]['modes']['paint'].get('same_color_noop') else 'Fallido', 'Relleno y repetición del mismo color ejecutados en una región interior real, Chrome.')
        set_control('T-17', 'Aprobado' if ex[slug]['modes']['brush'].get('passed') and all(by_engine[e][slug]['modes']['brush']['eraser']['changed'] for e in reports) else 'Fallido', 'Punto y borrador en Chrome/WebKit; trazo largo de 32 px cruzando líneas y borrado de 64 px en Chrome. Contornos negros sólidos intactos; no acredita gestos físicos ni todo grosor posible.')
        set_control('T-18', 'Aprobado' if all(m['undo_exact'] for e in reports for m in by_engine[e][slug]['modes'].values()) else 'Fallido', 'Deshacer devuelve el lienzo inicial exactamente en balde y pincel, ambos motores. Recuperación de reinicio no ejercitada por imagen.')
        set_control('T-19', 'Pendiente' if 'flutter' in row['platforms'] else 'Aprobado', 'Worker y fallback idénticos en la región seleccionada, Chrome y WebKit; todas las regiones geométricas probadas con motor compartido. Falta Flutter.' if 'flutter' in row['platforms'] else 'Worker y fallback idénticos en la región seleccionada, Chrome y WebKit; barrido geométrico con motor compartido.')
        exact = all(m['restore_exact'] for e in reports for m in by_engine[e][slug]['modes'].values())
        set_control('T-20', 'Aprobado' if exact else 'Fallido', 'Balde recuperado exactamente; pincel cambia píxeles al recuperar. Ver métricas por motor y PNG antes/después. El registro guardado sí coincide con el lienzo previo: el cambio ocurre al reconstruirlo.')
        set_control('T-21', 'Aprobado' if all(m.get('separate_saved_works') for m in ex[slug]['modes'].values()) else 'Fallido', 'Pintar A→pintar B→volver A; copias de ambos slugs coinciden con sus capturas independientes, por modo, Chrome. No implica recuperación visual correcta del pincel.')
        set_control('T-22', 'Pendiente' if all(d['pixels_exact'] for e in reports for m in by_engine[e][slug]['modes'].values() for d in m['downloads']) else 'Fallido', 'Parte automatizada aprobada: PNG recibido, decodificado y comparado píxel a píxel con el lienzo al descargar. Conserva el estado posterior a recuperar; no corrige T-20. Falta apertura independiente en visor del sistema por imagen/dispositivo.')
        set_control('T-23', 'Pendiente', 'Tres descargas consecutivas exactas por modo y motor; no se modificó la obra entre esas tres descargas. Faltan esa variante del caso y la alternativa física móvil.')
        set_control('T-24', 'Pendiente', 'No se imprimió ni se aprobó una variante destinada a papel.')
        set_control('T-25', 'Bloqueado', 'Escritorio automatizado Chrome y WebKit aprobado para carga/coloreado/exportación. Faltan Android/iPhone/iPad físicos y app Flutter.')
        set_control('T-26', 'Bloqueado', 'Esta ejecución por imagen usa 1280×900; no se probó rotación física, zoom ni desplazamiento por imagen.')
        set_control('T-27', 'Bloqueado', 'Hay tiempos de escritorio por imagen, pero falta equipo modesto y perfil de memoria. No compararlos como si fueran mediciones de Android.')
        set_control('T-28', 'Aprobado', 'Dimensiones, KB y SHA-256 por variante; tiempos de carga y barrido registrados. Memoria pendiente en T-27.')
        set_control('E-01', 'Pendiente' if slug == 'casa-4' else 'Aprobado', 'Figura vertical similar a torre/cohete; confirmar nombre Casa 4.' if slug == 'casa-4' else 'Revisión visual de dibujo/miniatura en hojas de contacto: tema principal reconocible. No es una valoración pedagógica.')
        set_control('E-02', 'Pendiente', 'Falta validar dificultad con el público previsto. ' + ('Nivel por-revisar en catálogo.' if row['difficulty'] == 'por-revisar' else f"Nivel declarado: {row['difficulty']}; revisar especialmente ponis y composiciones complejas."))
        set_control('E-03', 'Pendiente' if slug == 'casa-4' else 'Aprobado', 'Confirmar si Casa 4 corresponde a casas o a otra figura.' if slug == 'casa-4' else 'Categoría/pack revisados visualmente con la taxonomía actual; casas y paisajes tienen categorías propias.')
        set_control('E-04', 'Fallido' if slug in TEXT_MARKS else 'Pendiente' if slug in FRAGMENTED else 'Aprobado', TEXT_MARKS.get(slug, 'Artefactos/fragmentación requieren limpieza antes de aprobar presentación.' if slug in FRAGMENTED else 'Sin texto/marca visible que interfiera en la hoja de contacto; evaluación visual inicial, no certificación de derechos.'))
        set_control('P-01', 'Pendiente', 'Sin autor/fuente/evidencia por asset en el maestro. Créditos impresos son indicios de fuente, no un registro validado.')
        set_control('P-02', 'Bloqueado', 'Falta evidencia y validación del responsable para los usos previstos.')
        set_control('P-03', 'Bloqueado' if slug.startswith('gabby-') or slug.startswith('pony-') else 'Pendiente', 'Personajes o marcas reconocibles; falta acreditar permiso.' if slug.startswith('gabby-') or slug.startswith('pony-') else 'No se aprueba autorización por ausencia de una marca visible; falta revisión de procedencia.')
        set_control('P-04', 'Pendiente', 'No se aplicó una selección comercial ni se publicaron/excluyeron archivos; falta decisión acreditada de autorización.')
        assert set(controls) == set(titles), 'Checklist control coverage mismatch'
        notes = ['Fallo compartido del editor: recuperación de pincel altera bordes suavizados.']
        if slug == 'triceratops': notes.append('Fuga confirmada de cabeza al fondo: cerrar contorno antes de usar balde.')
        if slug in FRAGMENTED: notes.append('Limpiar fragmentación y regenerar variantes; volver a comprobar regiones.')
        if slug in TEXT_MARKS: notes.append(TEXT_MARKS[slug] + ' No eliminar créditos sin resolver condiciones de uso; preferir original autorizado.')
        if slug == 'casa-4': notes.append('Revisar nombre/taxonomía.')
        counts = Counter(c['status'] for c in controls.values())
        record = {**row, 'controls': controls, 'status_counts': dict(counts), 'notes': notes, 'technical_decision': 'Requiere corrección', 'publication_decision': 'No aprobada: procedencia y permisos pendientes'}
        records.append(record)
        lines = [f"# {row['label']} — {slug}", '', 'Revisión local: 07/10/2026. Responsable: Codex (comprobaciones automáticas y revisión visual).', '', '**Decisión técnica: requiere corrección.** Fallo del editor al recuperar pincel; además, ver controles fallidos propios del dibujo. **Publicación: pendiente de autorización.**', '', '## Archivos comprobados', '', '| Variante | Dimensiones | KB | Archivo |', '|---|---:|---:|---|']
        for role, f in row['files'].items(): lines.append(f"| {role} | {f['width']}×{f['height']} | {f['bytes']/1024:.1f} | [{Path(f['path']).name}](../../../../../{f['path']}) |")
        lines += ['', '## Hallazgos', ''] + ['- ' + note for note in notes]
        lines += ['', '## Resultados de recuperación y descarga', '', '| Motor | Balde: píxeles cambiados al recuperar | Pincel: píxeles cambiados | Delta máximo por canal en pincel | Descargas PNG exactas |', '|---|---:|---:|---:|---:|']
        for e in reports:
            r = by_engine[e][slug]['modes']; lines.append(f"| {e} | {r['paint']['restore_diff']['changed_pixels']} | {r['brush']['restore_diff']['changed_pixels']} | {r['brush']['restore_diff']['max_channel_delta']} | {sum(d['pixels_exact'] for m in r.values() for d in m['downloads'])}/6 |")
        lines += ['', f"Regiones geométricas: **{len(geometry['regions'])}**; menores de 16 px: **{geometry['regions_under_16px']}**. Barrido: {geometry['mismatched_pixels']} píxeles discrepantes y {geometry['damaged_line_pixels']} píxeles de contorno dañados. Esto prueba el algoritmo sobre la máscara; no valida qué zonas debían estar conectadas.", '', '[Mapa numerado](regions-chromium.png) · [Pincel antes de recuperar](brush-chromium-before-restore.png) · [Pincel recuperado/exportado](brush-chromium-export.png) · [Balde exportado](paint-chromium-export.png)', '', '## Checklist aplicado', '', '| ID | Control | Estado | Evidencia / limitación |', '|---|---|---|---|']
        for control, result in controls.items(): lines.append(f"| {control} | {titles[control]} | {result['status']} | {result['evidence']} |")
        (OUT / slug / 'CHECKLIST.md').write_text('\n'.join(lines)+'\n', encoding='utf-8')
        summary.append({'slug': slug, 'label': row['label'], 'regions': len(geometry['regions']), 'regions_under_16px': geometry['regions_under_16px'], 'approved': counts['Aprobado'], 'failed': counts['Fallido'], 'pending': counts['Pendiente'], 'blocked': counts['Bloqueado'], 'technical_decision': 'Requiere corrección', 'notes': ' / '.join(notes)})
    (OUT / 'checklist-results.json').write_text(json.dumps({'scope': '36 controls per image; no physical-device or permission approval', 'items': records}, ensure_ascii=False, indent=2), encoding='utf-8')
    with (OUT / 'checklist-summary.csv').open('w', encoding='utf-8-sig', newline='') as stream:
        writer = csv.DictWriter(stream, fieldnames=list(summary[0])); writer.writeheader(); writer.writerows(summary)
    all_downloads = sum(d['pixels_exact'] for e in reports for i in by_engine[e].values() for m in i['modes'].values() for d in m['downloads'])
    brush_deltas = [i['modes']['brush']['restore_diff']['changed_pixels'] for i in by_engine['chromium'].values()]
    report = ['# PaintMe — Resultado del checklist de imágenes', '', 'Fecha: 07/10/2026. Alcance: **62 dibujos del catálogo actual**, 43 incluidos también en Flutter y 19 solo web. Se aplicaron los **36 controles por imagen** y se registraron resultados, pendientes y bloqueos. No se modificaron imágenes ni código del producto.', '', '**Ningún dibujo obtiene aprobación técnica completa todavía:** todos reproducen un fallo compartido al recuperar el modo pincel; además faltan pruebas físicas y aprobación detallada de regiones esperadas. La autorización de publicación/comercialización sigue pendiente en los 62.', '', '## Resultados comprobados', '', f'- **229 archivos PNG** (maestros, web, miniaturas y variantes Flutter) decodificados con Pillow; todos legibles, con contenido visible, resolución y proporciones correctas. Las 43 variantes Flutter coinciden con las web por hash.', '- **62/62 dibujos** cargados y pintados en balde y pincel en Chrome y WebKit automatizados, con deshacer, guardado, recuperación y tres descargas por modo.', f'- **{all_downloads}/744 descargas PNG** recibidas y decodificadas: píxeles iguales al lienzo en el momento de descargar. El PNG del pincel conserva también cualquier alteración previa causada al recuperar.', f"- **{sum(len(i['geometry']['regions']) for i in by_engine['chromium'].values()):,} regiones geométricas** recorridas por el motor compartido en cada navegador, con cero píxeles discrepantes respecto a la conectividad de la máscara y sin dañar líneas. Esto no certifica ausencia de fugas: un contorno abierto produce una región conectada incorrecta que el algoritmo rellena correctamente.", '- Selección desde miniatura y selector, recoloreado, mismo color, protección al tocar líneas, trazo largo y separación A/B de guardados comprobados en Chrome por dibujo y modo.', '', '## Correcciones prioritarias', '', '1. **Editor pincel — T-20, 62 dibujos.** La copia persistida coincide con la obra, pero al recuperarla cambian píxeles de los bordes suavizados. Balde recupera exactamente. La ruta de restauración coloca el PNG compuesto en la capa de pintura, elimina parcialmente líneas y vuelve a componer; es coherente con el fallo observado. Corregir la reconstrucción o persistir la capa de pintura y repetir la matriz; no redibujar 62 assets por este defecto del editor.', '2. **Triceratops — T-08, T-13 y T-14.** La cabeza y el fondo comparten región. Un toque interior en (500,300), canvas 1200×1200, pinta ambos. [PNG que reproduce la fuga](qa-evidence/2026-10-07/artwork-checklist/triceratops-probe/triceratops/paint-chromium-export.png). Cerrar el contorno en el maestro y regenerar.', '3. **Siete imágenes — T-10.** Fragmentación abundante: limpiar ruido y pequeños recintos accidentales, revisar detalles relevantes y regenerar. El umbral de menos de 16 px es una señal diagnóstica; no es una medida validada de facilidad táctil.', '', '| Imagen | Regiones totales | Menores de 16 px |', '|---|---:|---:|']
    for slug in FRAGMENTED:
        g = by_engine['chromium'][slug]['geometry']; report.append(f"| [{slug}](qa-evidence/2026-10-07/artwork-checklist/{slug}/CHECKLIST.md) | {len(g['regions'])} | {g['regions_under_16px']} |")
    report += ['', f'4. **{len(TEXT_MARKS)} imágenes — E-04.** Textos de marca/créditos/sitios visibles, detallados en las fichas. Resolver procedencia y condiciones de uso; usar originales autorizados. La auditoría no autoriza borrar atribuciones.', '5. **Casa 4 — E-01/E-03 pendientes.** La figura parece una torre/cohete; confirmar nombre y clasificación. Dificultad y adecuación al público pendientes, especialmente ponis y composiciones Gabby.', '', f'En Chrome, recuperar pincel cambia entre **{min(brush_deltas):,} y {max(brush_deltas):,} píxeles por dibujo**, con delta máximo de 38 por canal. [Comparación ampliada antes/después](qa-evidence/2026-10-07/artwork-checklist/restore-comparison.png). Son diferencias en bordes, no evidencia de pérdida completa de la obra.', '', f"**Pipeline:** el generador señala {pipeline['byte_mismatches']} archivos diferentes por bytes. La comparación posterior confirma los mismos píxeles en los 11: diferencia de codificación PNG, sin cambio gráfico. [Detalle](qa-evidence/2026-10-07/artwork-checklist/pipeline-differences.json). No se regeneraron ni reemplazaron assets.", '', '## Qué queda sin aprobar', '', '- Regiones previstas y conexiones intencionales: mapas generados y revisados, pero no existe una referencia de intención gráfica aprobada para certificar todos los contornos. La fuga de Triceratops sí está confirmada.', '- Toque/zoom/rotación/exportación y memoria en Android, iPhone/iPad físicos; ejecución de los assets en Flutter; impresión.', '- WebKit en Windows no equivale a Safari iOS. Apertura de PNG en visor independiente y descargas con cambios entre repeticiones también pendientes.', '- Dificultad para la edad prevista, procedencia y permiso de publicación/adaptación/uso comercial. No se encontraron esos registros por imagen en el maestro; esto no demuestra falta de derechos ni una infracción.', '', '## Registro por imagen', '', '[Resumen CSV](qa-evidence/2026-10-07/artwork-checklist/checklist-summary.csv) · [Resultados completos JSON](qa-evidence/2026-10-07/artwork-checklist/checklist-results.json)', '', '| Imagen / ficha con 36 controles | Regiones | <16 px | Aprobados | Fallidos | Pendientes | Bloqueados |', '|---|---:|---:|---:|---:|---:|---:|']
    for row in summary: report.append(f"| [{row['label']}](qa-evidence/2026-10-07/artwork-checklist/{row['slug']}/CHECKLIST.md) | {row['regions']} | {row['regions_under_16px']} | {row['approved']} | {row['failed']} | {row['pending']} | {row['blocked']} |")
    report += ['', '## Evidencia y reproducción', '', '[Checklist original](CHECKLIST-IMAGENES-COLOREAR.md). Evidencia: [inventario](qa-evidence/2026-10-07/artwork-checklist/static.json), [Chrome](qa-evidence/2026-10-07/artwork-checklist/browser-chromium.json), [WebKit](qa-evidence/2026-10-07/artwork-checklist/browser-webkit.json), [casos adicionales Chrome](qa-evidence/2026-10-07/artwork-checklist/extended-chromium.json). Cada ficha enlaza PNG y mapa de regiones numeradas; regiones pequeñas de menos de 64 píxeles no llevan número dibujado, pero sí figuran en JSON.', '', 'Se conservan SHA-256 de fuentes, catálogos y scripts para identificar la revisión local. Las pruebas sirven `web/` por HTTPS local y bloquean terceros. No miden producción ni anuncios. La auditoría compara píxeles; no interpreta como defectos diferencias de compresión PNG.', '', '```powershell', 'python scripts/build_catalog.py', 'python scripts/audit-artwork-static.py', "$env:PAINTME_PLAYWRIGHT_PATH = '<ruta instalada a playwright>'", "$env:PAINTME_BROWSER_ENGINE = 'chromium'", 'node scripts/audit-artwork-browser.cjs', 'node scripts/audit-artwork-browser.cjs --extended', "$env:PAINTME_BROWSER_ENGINE = 'webkit'", 'node scripts/audit-artwork-browser.cjs', "$env:PAINTME_BROWSER_ENGINE = 'chromium'", 'node scripts/audit-artwork-browser.cjs --probe-triceratops', 'python scripts/artwork-audit-contact-sheets.py', 'python scripts/summarize-artwork-checklist.py', '```', '', 'El runner devuelve **código 1** cuando reproduce un control funcional fallido (en esta revisión, recuperación de pincel). Es un resultado negativo registrado, no un fallo que deba ocultarse. Genera y reemplaza evidencia automática; preservar una ejecución anterior en otra carpeta antes de repetir si se desea conservar historial.']
    report.insert(report.index('python scripts/summarize-artwork-checklist.py'), 'python scripts/compare-artwork-pipeline.py')
    (ROOT / 'docs/RESULTADO-CHECKLIST-IMAGENES.md').write_text('\n'.join(report)+'\n', encoding='utf-8')
    print(f'{len(records)} fichas, {len(records)*len(titles)} controles, resumen y evidencia indexados.')

if __name__ == '__main__':
    main()
