// Generated by scripts/build_catalog.py; edit base_png/catalog.json.
window.ASSETS = [
  {
    "label": "Dinosaurio feliz",
    "slug": "dinosaurio",
    "category": "dinosaurios",
    "pack": "dinosaurios",
    "theme": "dinosaurios",
    "difficulty": "medio",
    "keywords": [
      "dinosaurio",
      "feliz",
      "dinosaurios"
    ],
    "featured": true,
    "src": "assets/dinosaur-v2.png",
    "thumbnailSrc": "assets/thumbs/dinosaur-v2.png",
    "description": "Dinosaurio feliz: dibujo para colorear en Dinosaurios."
  },
  {
    "label": "Gato curioso",
    "slug": "gato",
    "category": "animales",
    "pack": "animales",
    "theme": "animales",
    "difficulty": "medio",
    "keywords": [
      "gato",
      "curioso",
      "animales"
    ],
    "featured": true,
    "src": "assets/cat-v2.png",
    "thumbnailSrc": "assets/thumbs/cat-v2.png",
    "description": "Gato curioso: dibujo para colorear en Animales."
  },
  {
    "label": "Perro juguetón",
    "slug": "perro",
    "category": "animales",
    "pack": "animales",
    "theme": "animales",
    "difficulty": "medio",
    "keywords": [
      "perro",
      "jugueton",
      "animales"
    ],
    "featured": true,
    "src": "assets/dog-v2.png",
    "thumbnailSrc": "assets/thumbs/dog-v2.png",
    "description": "Perro juguetón: dibujo para colorear en Animales."
  },
  {
    "label": "Auto rojo",
    "slug": "auto",
    "category": "vehiculos",
    "pack": "vehiculos",
    "theme": "vehiculos",
    "difficulty": "medio",
    "keywords": [
      "auto",
      "rojo",
      "vehiculos"
    ],
    "featured": true,
    "src": "assets/car-v2.png",
    "thumbnailSrc": "assets/thumbs/car-v2.png",
    "description": "Auto rojo: dibujo para colorear en Vehículos."
  },
  {
    "label": "Árbol de navidad",
    "slug": "arbol-navidad",
    "category": "navidad",
    "pack": "navidad",
    "theme": "navidad",
    "difficulty": "medio",
    "keywords": [
      "arbol",
      "de",
      "navidad"
    ],
    "featured": true,
    "src": "assets/christmas-tree-v2.png",
    "thumbnailSrc": "assets/thumbs/christmas-tree-v2.png",
    "description": "Árbol de navidad: dibujo para colorear en Navidad."
  },
  {
    "label": "Mariposa",
    "slug": "mariposa",
    "category": "animales",
    "pack": "animales",
    "theme": "animales",
    "difficulty": "medio",
    "keywords": [
      "mariposa",
      "animales"
    ],
    "featured": true,
    "src": "assets/butterfly-v2.png",
    "thumbnailSrc": "assets/thumbs/butterfly-v2.png",
    "description": "Mariposa: dibujo para colorear en Animales."
  },
  {
    "label": "Cohete",
    "slug": "cohete",
    "category": "vehiculos",
    "pack": "vehiculos",
    "theme": "vehiculos",
    "difficulty": "medio",
    "keywords": [
      "cohete",
      "vehiculos"
    ],
    "featured": true,
    "src": "assets/rocket-v2.png",
    "thumbnailSrc": "assets/thumbs/rocket-v2.png",
    "description": "Cohete: dibujo para colorear en Vehículos."
  },
  {
    "label": "Princesa",
    "slug": "princesa",
    "category": "princesas",
    "pack": "princesas",
    "theme": "princesas",
    "difficulty": "medio",
    "keywords": [
      "princesa",
      "princesas"
    ],
    "featured": true,
    "src": "assets/princess-v2.png",
    "thumbnailSrc": "assets/thumbs/princess-v2.png",
    "description": "Princesa: dibujo para colorear en Princesas."
  },
  {
    "label": "Unicornio",
    "slug": "unicornio",
    "category": "fantasia",
    "pack": "fantasia",
    "theme": "fantasia",
    "difficulty": "medio",
    "keywords": [
      "unicornio",
      "fantasia"
    ],
    "featured": true,
    "src": "assets/unicorn-v2.png",
    "thumbnailSrc": "assets/thumbs/unicorn-v2.png",
    "description": "Unicornio: dibujo para colorear en Fantasía."
  },
  {
    "label": "Castillo",
    "slug": "castillo",
    "category": "fantasia",
    "pack": "fantasia",
    "theme": "fantasia",
    "difficulty": "medio",
    "keywords": [
      "castillo",
      "fantasia"
    ],
    "featured": true,
    "src": "assets/castle-v2.png",
    "thumbnailSrc": "assets/thumbs/castle-v2.png",
    "description": "Castillo: dibujo para colorear en Fantasía."
  },
  {
    "label": "Elefante alegre",
    "slug": "elefante",
    "category": "animales",
    "pack": "animales",
    "theme": "animales",
    "difficulty": "medio",
    "keywords": [
      "elefante",
      "alegre",
      "animales"
    ],
    "featured": false,
    "src": "assets/elefante.png",
    "thumbnailSrc": "assets/thumbs/elefante.png",
    "description": "Elefante alegre: dibujo para colorear en Animales."
  },
  {
    "label": "Conejo saltarín",
    "slug": "conejo",
    "category": "animales",
    "pack": "animales",
    "theme": "animales",
    "difficulty": "medio",
    "keywords": [
      "conejo",
      "saltarin",
      "animales"
    ],
    "featured": false,
    "src": "assets/conejo.png",
    "thumbnailSrc": "assets/thumbs/conejo.png",
    "description": "Conejo saltarín: dibujo para colorear en Animales."
  },
  {
    "label": "Pez sonriente",
    "slug": "pez",
    "category": "animales",
    "pack": "animales",
    "theme": "animales",
    "difficulty": "medio",
    "keywords": [
      "pez",
      "sonriente",
      "animales"
    ],
    "featured": false,
    "src": "assets/pez.png",
    "thumbnailSrc": "assets/thumbs/pez.png",
    "description": "Pez sonriente: dibujo para colorear en Animales."
  },
  {
    "label": "Búho amable",
    "slug": "buho",
    "category": "animales",
    "pack": "animales",
    "theme": "animales",
    "difficulty": "medio",
    "keywords": [
      "buho",
      "amable",
      "animales"
    ],
    "featured": false,
    "src": "assets/buho.png",
    "thumbnailSrc": "assets/thumbs/buho.png",
    "description": "Búho amable: dibujo para colorear en Animales."
  },
  {
    "label": "Camión feliz",
    "slug": "camion",
    "category": "vehiculos",
    "pack": "vehiculos",
    "theme": "vehiculos",
    "difficulty": "medio",
    "keywords": [
      "camion",
      "feliz",
      "vehiculos"
    ],
    "featured": false,
    "src": "assets/camion.png",
    "thumbnailSrc": "assets/thumbs/camion.png",
    "description": "Camión feliz: dibujo para colorear en Vehículos."
  },
  {
    "label": "Avión divertido",
    "slug": "avion",
    "category": "vehiculos",
    "pack": "vehiculos",
    "theme": "vehiculos",
    "difficulty": "medio",
    "keywords": [
      "avion",
      "divertido",
      "vehiculos"
    ],
    "featured": false,
    "src": "assets/avion.png",
    "thumbnailSrc": "assets/thumbs/avion.png",
    "description": "Avión divertido: dibujo para colorear en Vehículos."
  },
  {
    "label": "Barco de vela",
    "slug": "barco",
    "category": "vehiculos",
    "pack": "vehiculos",
    "theme": "vehiculos",
    "difficulty": "medio",
    "keywords": [
      "barco",
      "de",
      "vela",
      "vehiculos"
    ],
    "featured": false,
    "src": "assets/barco.png",
    "thumbnailSrc": "assets/thumbs/barco.png",
    "description": "Barco de vela: dibujo para colorear en Vehículos."
  },
  {
    "label": "Tren juguete",
    "slug": "tren",
    "category": "vehiculos",
    "pack": "vehiculos",
    "theme": "vehiculos",
    "difficulty": "medio",
    "keywords": [
      "tren",
      "juguete",
      "vehiculos"
    ],
    "featured": false,
    "src": "assets/tren.png",
    "thumbnailSrc": "assets/thumbs/tren.png",
    "description": "Tren juguete: dibujo para colorear en Vehículos."
  },
  {
    "label": "Muñeco de nieve",
    "slug": "muneco-nieve",
    "category": "navidad",
    "pack": "navidad",
    "theme": "navidad",
    "difficulty": "medio",
    "keywords": [
      "muneco",
      "de",
      "nieve",
      "navidad"
    ],
    "featured": false,
    "src": "assets/muneco-nieve.png",
    "thumbnailSrc": "assets/thumbs/muneco-nieve.png",
    "description": "Muñeco de nieve: dibujo para colorear en Navidad."
  },
  {
    "label": "Regalo navideño",
    "slug": "regalo-navidad",
    "category": "navidad",
    "pack": "navidad",
    "theme": "navidad",
    "difficulty": "medio",
    "keywords": [
      "regalo",
      "navideno",
      "navidad"
    ],
    "featured": false,
    "src": "assets/regalo-navidad.png",
    "thumbnailSrc": "assets/thumbs/regalo-navidad.png",
    "description": "Regalo navideño: dibujo para colorear en Navidad."
  },
  {
    "label": "Campana navideña",
    "slug": "campana-navidad",
    "category": "navidad",
    "pack": "navidad",
    "theme": "navidad",
    "difficulty": "medio",
    "keywords": [
      "campana",
      "navidena",
      "navidad"
    ],
    "featured": false,
    "src": "assets/campana-navidad.png",
    "thumbnailSrc": "assets/thumbs/campana-navidad.png",
    "description": "Campana navideña: dibujo para colorear en Navidad."
  },
  {
    "label": "Dragón bebé",
    "slug": "dragon",
    "category": "fantasia",
    "pack": "fantasia",
    "theme": "fantasia",
    "difficulty": "medio",
    "keywords": [
      "dragon",
      "bebe",
      "fantasia"
    ],
    "featured": false,
    "src": "assets/dragon.png",
    "thumbnailSrc": "assets/thumbs/dragon.png",
    "description": "Dragón bebé: dibujo para colorear en Fantasía."
  },
  {
    "label": "Hada mágica",
    "slug": "hada",
    "category": "fantasia",
    "pack": "fantasia",
    "theme": "fantasia",
    "difficulty": "medio",
    "keywords": [
      "hada",
      "magica",
      "fantasia"
    ],
    "featured": false,
    "src": "assets/hada.png",
    "thumbnailSrc": "assets/thumbs/hada.png",
    "description": "Hada mágica: dibujo para colorear en Fantasía."
  },
  {
    "label": "Sirena feliz",
    "slug": "sirena",
    "category": "fantasia",
    "pack": "fantasia",
    "theme": "fantasia",
    "difficulty": "medio",
    "keywords": [
      "sirena",
      "feliz",
      "fantasia"
    ],
    "featured": false,
    "src": "assets/sirena.png",
    "thumbnailSrc": "assets/thumbs/sirena.png",
    "description": "Sirena feliz: dibujo para colorear en Fantasía."
  },
  {
    "label": "Triceratops",
    "slug": "triceratops",
    "category": "dinosaurios",
    "pack": "dinosaurios",
    "theme": "dinosaurios",
    "difficulty": "medio",
    "keywords": [
      "triceratops",
      "dinosaurios"
    ],
    "featured": false,
    "src": "assets/triceratops.png",
    "thumbnailSrc": "assets/thumbs/triceratops.png",
    "description": "Triceratops: dibujo para colorear en Dinosaurios."
  },
  {
    "label": "Brontosaurio",
    "slug": "brontosaurio",
    "category": "dinosaurios",
    "pack": "dinosaurios",
    "theme": "dinosaurios",
    "difficulty": "medio",
    "keywords": [
      "brontosaurio",
      "dinosaurios"
    ],
    "featured": false,
    "src": "assets/brontosaurio.png",
    "thumbnailSrc": "assets/thumbs/brontosaurio.png",
    "description": "Brontosaurio: dibujo para colorear en Dinosaurios."
  },
  {
    "label": "Pterodáctilo",
    "slug": "pterodactilo",
    "category": "dinosaurios",
    "pack": "dinosaurios",
    "theme": "dinosaurios",
    "difficulty": "medio",
    "keywords": [
      "pterodactilo",
      "dinosaurios"
    ],
    "featured": false,
    "src": "assets/pterodactilo.png",
    "thumbnailSrc": "assets/thumbs/pterodactilo.png",
    "description": "Pterodáctilo: dibujo para colorear en Dinosaurios."
  },
  {
    "label": "Corona real",
    "slug": "corona-real",
    "category": "princesas",
    "pack": "princesas",
    "theme": "princesas",
    "difficulty": "medio",
    "keywords": [
      "corona",
      "real",
      "princesas"
    ],
    "featured": false,
    "src": "assets/corona-real.png",
    "thumbnailSrc": "assets/thumbs/corona-real.png",
    "description": "Corona real: dibujo para colorear en Princesas."
  },
  {
    "label": "Carruaje real",
    "slug": "carruaje-real",
    "category": "princesas",
    "pack": "princesas",
    "theme": "princesas",
    "difficulty": "medio",
    "keywords": [
      "carruaje",
      "real",
      "princesas"
    ],
    "featured": false,
    "src": "assets/carruaje-real.png",
    "thumbnailSrc": "assets/thumbs/carruaje-real.png",
    "description": "Carruaje real: dibujo para colorear en Princesas."
  },
  {
    "label": "Vestido de princesa",
    "slug": "vestido-princesa",
    "category": "princesas",
    "pack": "princesas",
    "theme": "princesas",
    "difficulty": "medio",
    "keywords": [
      "vestido",
      "de",
      "princesa",
      "princesas"
    ],
    "featured": false,
    "src": "assets/vestido-princesa.png",
    "thumbnailSrc": "assets/thumbs/vestido-princesa.png",
    "description": "Vestido de princesa: dibujo para colorear en Princesas."
  },
  {
    "label": "Pony mágico",
    "slug": "pony-magico",
    "category": "fantasia",
    "pack": "fantasia",
    "theme": "fantasia",
    "difficulty": "medio",
    "keywords": [
      "pony",
      "magico",
      "fantasia"
    ],
    "featured": false,
    "src": "assets/pony1.png",
    "thumbnailSrc": "assets/thumbs/pony1.png",
    "description": "Pony mágico: dibujo para colorear en Fantasía."
  },
  {
    "label": "Pony princesa",
    "slug": "pony-princesa",
    "category": "princesas",
    "pack": "princesas",
    "theme": "princesas",
    "difficulty": "medio",
    "keywords": [
      "pony",
      "princesa",
      "princesas"
    ],
    "featured": false,
    "src": "assets/pony2.png",
    "thumbnailSrc": "assets/thumbs/pony2.png",
    "description": "Pony princesa: dibujo para colorear en Princesas."
  },
  {
    "label": "Pony 3",
    "slug": "pony-3",
    "category": "fantasia",
    "pack": "fantasia",
    "theme": "fantasia",
    "difficulty": "medio",
    "keywords": [
      "pony",
      "3",
      "fantasia"
    ],
    "featured": false,
    "src": "assets/pony3.png",
    "thumbnailSrc": "assets/thumbs/pony3.png",
    "description": "Pony 3: dibujo para colorear en Fantasía."
  },
  {
    "label": "Pony 4",
    "slug": "pony-4",
    "category": "fantasia",
    "pack": "fantasia",
    "theme": "fantasia",
    "difficulty": "medio",
    "keywords": [
      "pony",
      "4",
      "fantasia"
    ],
    "featured": false,
    "src": "assets/pony4.png",
    "thumbnailSrc": "assets/thumbs/pony4.png",
    "description": "Pony 4: dibujo para colorear en Fantasía."
  },
  {
    "label": "Casa 1",
    "slug": "casa-1",
    "category": "casas",
    "pack": "casas",
    "theme": "casas",
    "difficulty": "simple",
    "keywords": [
      "casa",
      "1",
      "navidad",
      "casas"
    ],
    "featured": false,
    "src": "assets/house1.png",
    "thumbnailSrc": "assets/thumbs/house1.png",
    "description": "Casa 1: dibujo para colorear en Casas."
  },
  {
    "label": "Casa 2",
    "slug": "casa-2",
    "category": "casas",
    "pack": "casas",
    "theme": "casas",
    "difficulty": "simple",
    "keywords": [
      "casa",
      "2",
      "navidad",
      "casas"
    ],
    "featured": false,
    "src": "assets/house2.png",
    "thumbnailSrc": "assets/thumbs/house2.png",
    "description": "Casa 2: dibujo para colorear en Casas."
  },
  {
    "label": "Casa 3",
    "slug": "casa-3",
    "category": "casas",
    "pack": "casas",
    "theme": "casas",
    "difficulty": "simple",
    "keywords": [
      "casa",
      "3",
      "navidad",
      "casas"
    ],
    "featured": false,
    "src": "assets/house3.png",
    "thumbnailSrc": "assets/thumbs/house3.png",
    "description": "Casa 3: dibujo para colorear en Casas."
  },
  {
    "label": "Cohete sencillo",
    "slug": "casa-4",
    "category": "vehiculos",
    "pack": "vehiculos",
    "theme": "vehiculos",
    "difficulty": "simple",
    "keywords": [
      "cohete",
      "sencillo",
      "vehiculos"
    ],
    "featured": false,
    "src": "assets/house4.png",
    "thumbnailSrc": "assets/thumbs/house4.png",
    "description": "Cohete sencillo: dibujo para colorear en Vehículos."
  },
  {
    "label": "Casa 5",
    "slug": "casa-5",
    "category": "casas",
    "pack": "casas",
    "theme": "casas",
    "difficulty": "simple",
    "keywords": [
      "casa",
      "5",
      "navidad",
      "casas"
    ],
    "featured": false,
    "src": "assets/house5.png",
    "thumbnailSrc": "assets/thumbs/house5.png",
    "description": "Casa 5: dibujo para colorear en Casas."
  },
  {
    "label": "Paisaje 3",
    "slug": "paisaje-3",
    "category": "paisajes",
    "pack": "paisajes",
    "theme": "paisajes",
    "difficulty": "simple",
    "keywords": [
      "paisaje",
      "3",
      "animales",
      "paisajes"
    ],
    "featured": false,
    "src": "assets/landscape3.png",
    "thumbnailSrc": "assets/thumbs/landscape3.png",
    "description": "Paisaje 3: dibujo para colorear en Paisajes."
  },
  {
    "label": "Paisaje 4",
    "slug": "paisaje-4",
    "category": "paisajes",
    "pack": "paisajes",
    "theme": "paisajes",
    "difficulty": "simple",
    "keywords": [
      "paisaje",
      "4",
      "animales",
      "paisajes"
    ],
    "featured": false,
    "src": "assets/landscape4.png",
    "thumbnailSrc": "assets/thumbs/landscape4.png",
    "description": "Paisaje 4: dibujo para colorear en Paisajes."
  },
  {
    "label": "Paisaje 5",
    "slug": "paisaje-5",
    "category": "paisajes",
    "pack": "paisajes",
    "theme": "paisajes",
    "difficulty": "simple",
    "keywords": [
      "paisaje",
      "5",
      "animales",
      "paisajes"
    ],
    "featured": false,
    "src": "assets/landscape5.png",
    "thumbnailSrc": "assets/thumbs/landscape5.png",
    "description": "Paisaje 5: dibujo para colorear en Paisajes."
  },
  {
    "label": "Casa simple",
    "slug": "casa-simple",
    "category": "casas",
    "pack": "casas",
    "theme": "casas",
    "difficulty": "simple",
    "keywords": [
      "casa",
      "simple",
      "navidad",
      "casas"
    ],
    "featured": false,
    "src": "assets/outline_house.png",
    "thumbnailSrc": "assets/thumbs/outline_house.png",
    "description": "Casa simple: dibujo para colorear en Casas."
  },
  {
    "label": "Gabby gato volador",
    "slug": "gabby-gato-volador",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "gato",
      "volador"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-01-gato-volador.png",
    "thumbnailSrc": "assets/thumbs/gabby-01-gato-volador.png",
    "description": "Gabby gato volador: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby gato con flores",
    "slug": "gabby-gato-flores",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "gato",
      "flores"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-02-gato-flores.png",
    "thumbnailSrc": "assets/thumbs/gabby-02-gato-flores.png",
    "description": "Gabby gato con flores: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby auto",
    "slug": "gabby-auto",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "auto"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-03-auto.png",
    "thumbnailSrc": "assets/thumbs/gabby-03-auto.png",
    "description": "Gabby auto: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby camping",
    "slug": "gabby-camping",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "camping"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-04-camping.png",
    "thumbnailSrc": "assets/thumbs/gabby-04-camping.png",
    "description": "Gabby camping: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby casa y auto",
    "slug": "gabby-casa-auto",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "casa",
      "auto"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-05-casa-y-auto.png",
    "thumbnailSrc": "assets/thumbs/gabby-05-casa-y-auto.png",
    "description": "Gabby casa y auto: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby pintando",
    "slug": "gabby-pintando",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "pintando",
      "arte"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-06-pintando.png",
    "thumbnailSrc": "assets/thumbs/gabby-06-pintando.png",
    "description": "Gabby pintando: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby gato espacial",
    "slug": "gabby-gato-espacial",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "gato",
      "espacio"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-07-gato-espacial.png",
    "thumbnailSrc": "assets/thumbs/gabby-07-gato-espacial.png",
    "description": "Gabby gato espacial: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby leyendo",
    "slug": "gabby-leyendo",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "leyendo",
      "libro"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-08-leyendo.png",
    "thumbnailSrc": "assets/thumbs/gabby-08-leyendo.png",
    "description": "Gabby leyendo: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby gato simple",
    "slug": "gabby-gato-simple",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "gato"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-09-gato-simple.png",
    "thumbnailSrc": "assets/thumbs/gabby-09-gato-simple.png",
    "description": "Gabby gato simple: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby amigos",
    "slug": "gabby-amigos",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "amigos"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-10-amigos.png",
    "thumbnailSrc": "assets/thumbs/gabby-10-amigos.png",
    "description": "Gabby amigos: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby sala",
    "slug": "gabby-sala",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "sala",
      "casa"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-11-sala.png",
    "thumbnailSrc": "assets/thumbs/gabby-11-sala.png",
    "description": "Gabby sala: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby gato disfrazado",
    "slug": "gabby-gato-disfraz",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "gato",
      "disfraz"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-12-gato-disfraz.png",
    "thumbnailSrc": "assets/thumbs/gabby-12-gato-disfraz.png",
    "description": "Gabby gato disfrazado: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby cumpleaños",
    "slug": "gabby-cumpleanos",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "cumpleanos",
      "fiesta"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-13-cumpleanos.png",
    "thumbnailSrc": "assets/thumbs/gabby-13-cumpleanos.png",
    "description": "Gabby cumpleaños: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby Catrat",
    "slug": "gabby-catrat",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "catrat",
      "gato"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-14-catrat.png",
    "thumbnailSrc": "assets/thumbs/gabby-14-catrat.png",
    "description": "Gabby Catrat: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby gato espacial dos",
    "slug": "gabby-gato-espacial-2",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "gato",
      "espacio"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-15-gato-espacial-2.png",
    "thumbnailSrc": "assets/thumbs/gabby-15-gato-espacial-2.png",
    "description": "Gabby gato espacial dos: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby gato caja",
    "slug": "gabby-gato-caja",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "gato",
      "caja"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-16-gato-caja.png",
    "thumbnailSrc": "assets/thumbs/gabby-16-gato-caja.png",
    "description": "Gabby gato caja: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby póster de amigos",
    "slug": "gabby-poster-amigos",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "poster",
      "amigos"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-17-poster-amigos.png",
    "thumbnailSrc": "assets/thumbs/gabby-17-poster-amigos.png",
    "description": "Gabby póster de amigos: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby casa mágica",
    "slug": "gabby-casa-magica",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "casa",
      "magica"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-18-casa-magica.png",
    "thumbnailSrc": "assets/thumbs/gabby-18-casa-magica.png",
    "description": "Gabby casa mágica: dibujo para colorear en Gabby."
  },
  {
    "label": "Gabby casa frontal",
    "slug": "gabby-casa-frontal",
    "category": "gabby",
    "pack": "gabby",
    "theme": "gabby",
    "difficulty": "por-revisar",
    "keywords": [
      "gabby",
      "casa"
    ],
    "featured": false,
    "src": "assets/gabby/gabby-19-casa-frontal.png",
    "thumbnailSrc": "assets/thumbs/gabby-19-casa-frontal.png",
    "description": "Gabby casa frontal: dibujo para colorear en Gabby."
  }
];
